---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: headers
spec:
  location: global
  resourceID: headers
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headers
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: headers
spec:
  rules:
  - host: headers.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: headers
            port:
              number: 80
  - host: header-unmatch.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: header-unmatch
            port:
              number: 80
  - host: header-match.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: header-match
            port:
              number: 80
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  name: headers
spec:
  rule:
  - action: redirect
    priority: 0
    match:
      expr:
        expression: |
          has(request.headers['Foo']) && request.headers['Foo'].matches('[Bb]ar')
    redirectOptions:
      target: "http://header-match.example.com"
      type: EXTERNAL_302
  - action: redirect
    priority: 2147483647
    match:
      versionedExpr: SRC_IPS_V1
      config:
        srcIpRanges:
        - "*"
    redirectOptions:
      target: "http://header-unmatch.example.com"
      type: EXTERNAL_302
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: headers
spec:
  securityPolicy:
    name: "headers"
---
apiVersion: v1
kind: Service
metadata:
  name: headers
  annotations:
    cloud.google.com/backend-config: '{"default": "headers"}'
spec:
  type: NodePort
  selector:
    app: headers
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headers
  labels:
    app: headers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headers
  template:
    metadata:
      labels:
        app: headers
    spec:
      containers:
      - name: echo
        image: mendhak/http-https-echo:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
---
apiVersion: v1
kind: Service
metadata:
  name: header-match
spec:
  type: NodePort
  selector:
    app: header-match
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-match
  labels:
    app: header-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: header-match
  template:
    metadata:
      labels:
        app: header-match
    spec:
      containers:
      - name: echo
        image: mendhak/http-https-echo:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
---
apiVersion: v1
kind: Service
metadata:
  name: header-unmatch
spec:
  type: NodePort
  selector:
    app: header-unmatch
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-unmatch
  labels:
    app: header-unmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: header-unmatch
  template:
    metadata:
      labels:
        app: header-unmatch
    spec:
      containers:
      - name: echo
        image: mendhak/http-https-echo:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"